project:
  type: website
  output-dir: docs

website:
  title: "Kandace Loualhati"
    navbar:
    left:
      - href: index.qmd
        text: "About Me"
      - about.qmd
        text: "Data Viz"
        menu: 
          - text: "Average Tuition"
            href: averagetuition.html
          - text: "Something Else"

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

