project:
  type: website
  output-dir: docs

website:
  title: "Kandace Loualhati"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dataviz.qmd
      title: "State Tuition"
      description: \|
      Analysis of US average tuition by state data from TidyTuesday
      author: Tom Mock
      date: April 4th, 2018
      format: html
      menu: 
      - text: 

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

