project:
  type: website
  output-dir: docs

website:
  title: "Kandace Loualhati"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dataviz.qmd
      menu: 
      - text: 

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

